export type { SceneRoot } from './scene/build-scene'
export { buildScene } from './scene/build-scene'
export { sceneBounds } from './scene/scene-bounds'
export { markShadowCasters } from './scene/shadow-casters'
export type { OrbitController } from './scene/orbit-controls'
export { createOrbitController } from './scene/orbit-controls'
export type { LightingProvider } from './lighting/lighting-provider'
export { BasicLightingProvider } from './lighting/basic-lighting-provider'
export { setLightingColor, removeLighting, fitSunShadowToBounds } from './lighting/lighting-rig'
export type { RenderBackend } from './renderer/detect-backend'
export { detectRenderBackend } from './renderer/detect-backend'
export type { SceneRendererOptions } from './renderer/create-renderer'
export { createSceneRenderer } from './renderer/create-renderer'
export type { MaterialProvider, SurfaceRole } from './materials/material-provider'
export { NeutralMaterialProvider } from './materials/neutral-material-provider'
export type { PaintMaterialOptions } from './materials/paint-material-provider'
export { PaintMaterialProvider } from './materials/paint-material-provider'
